### PR TITLE
feat: improve top-level Query and Mutation type handling

### PR DESCRIPTION
**Pull request by danadajian**
### :pencil: Description
- Includes a generated class per field for the top-level `Query` and `Mutation` types.
- Includes the `Query` and `Mutation` types in `resolverInterfaces` by default.

### :link: Related Issues
- #71

### CODE REVIEW

**Review by MicahWitthaus — COMMENTED** [review]
I see there is an `expected.kt` for the new query field classes but I didn't see any tests using it in this PR. Are the tests generated somewhere in this repo?

**Comment by danadajian** [comment]
> I see there is an `expected.kt` for the new query field classes but I didn't see any tests using it in this PR. Are the tests generated somewhere in this repo?

So each directory in the `unit/` folder contains an `expected.kt` and `schema.graphql` file. The `schema.graphql` file should generate the `expected.kt`

**Comment by MicahWitthaus** [comment]
> So each directory in the `unit/` folder contains an `expected.kt` and `schema.graphql` file. The `schema.graphql` file should generate the `expected.kt`

@danadajian Gotcha, so there are no assertions checking that the `schema.graphql` file actually generates the `expected.kt` contents?

**Comment by danadajian** [comment]
> > So each directory in the `unit/` folder contains an `expected.kt` and `schema.graphql` file. The `schema.graphql` file should generate the `expected.kt`
> 
> @danadajian Gotcha, so there are no assertions checking that the `schema.graphql` file actually generates the `expected.kt` contents?

There are, they are just done in a slightly abstract way in [plugin.test.ts](https://github.com/ExpediaGroup/graphql-kotlin-codegen/blob/main/test/plugin.test.ts)

**Review by MicahWitthaus — APPROVED** [review]

**Pull request merged**
